### PR TITLE
Bugfixes: Log seconds missing, Log timezone wrong, Characters not animating

### PR DESCRIPTION
**Pull request by milan60**
It looks like my "fix" for the EST timestamp accidentally removed the seconds from the log (which are quite important for research). This commit brings them back.

Regarding the incorrect timestamp, it looks like the timestamp is somehow in EST, I don't know how one could fix that bug without an ugly workaround.

### CODE REVIEW

**Comment by milan60** [comment]
I tested my change to the LogController.php. It's a working fix for the incorrect timestamp bug. The issue was that the MySQL servers timezone is set to EST, so I modified the query to convert it to UTC. My fix prevents having to set a timezone manually and just converts whatever timezone the MySQL server uses to UTC.

I tested it in a local instance and it works.

**Comment by milan60** [comment]
@ExpDev07 Recent commit also fixes Issue #91. All commits have been tested.

**Comment by milan60** [comment]
This could potentially fix #70 would have to be checked in the live server though.

**Comment by milan60** [comment]
warnings  
logs

**Comment by ExpDev07** [comment]
Looks good! Merging.

**Pull request merged**
