### PR TITLE
StaffPM and Twitter Feed

### PR DESCRIPTION
**Pull request by milan60**
### Changelog

 - Add ability to staffPM
- Add panel_logs
- Refactoring
- Bugfixing
- Twitter Feed

@ExpDev07 if you could take a look at it and merge it :)

### CODE REVIEW

**Comment by ExpDev07** [comment]
Hello you've been doing great work on the admin panel. Lots of new great features.

Just wondering, if I were to set this up locally now, would I have to do anything extra than php artisan migrate + normal commands and spin it up? Or does it require any additional env variables/keys set?

**Comment by milan60** [comment]
@ExpDev07
Few new variables in the .env:
```
VUE_APP_LOCALE=en-us the frontend locale

# OP-FW configuration
OP_FW_SERVERS=c3s1.op-framework.com,c2s1.op-framework.com
OP_FW_TOKEN=token for executing kick and staffpm using the servers api
DEV_API_KEY=token with which you can download logs (for developers)
```

Also, you will have to redo your database as I fixed all the migrations recently. You need to drop all your tables pretty much and run all migrations again.

**Comment by ExpDev07** [comment]
@milan60 awesome, would the panel crash without those keys or would only certain parts not work?

**Comment by milan60** [comment]
@ExpDev07 only certain parts wont work. `VUE_APP_LOCALE=en-us` should be set otherwise all texts will be "MISSING_LOCALE"

**Pull request merged**
